# Import Library and Models

In [13]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

#import Categorical Naive Bayes Model
from sklearn.naive_bayes import CategoricalNB

#import Logistic Regression model 
from sklearn.linear_model import LogisticRegression

#import Decision Tree model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Import Dataset

In [14]:
data = pd.read_csv("student_digital_life.csv",  sep=",")

# Display Dataset information

In [15]:
display(data.head())
display(data.info())
display(data.describe(include="all"))

,student_id,age,gender,study_hours_per_day,smartphone_usage_hours,social_media_hours,gaming_hours,streaming_hours,sleep_hours,exercise_hours,class_attendance_percent,assignment_completion_percent,caffeine_intake_cups,mental_health_status,parent_education_level,internet_quality,motivation_level,final_exam_score
0,1,21,Female,3.01,0.26,1.77,0.26,1.71,5.32,0.70,64.87,74.11,2,Good,Masters,Average,6.32,82.70
1,2,23,Female,5.84,8.02,3.30,0.96,0.00,5.99,1.99,85.38,80.68,3,Average,Masters,Poor,2.52,85.65
2,3,20,Female,7.80,10.13,0.00,2.23,2.54,6.36,1.82,76.15,79.69,2,Good,HighSchool,Poor,3.98,88.14
3,4,20,Female,0.00,1.15,1.32,4.19,0.27,7.86,0.18,84.41,79.07,0,Average,HighSchool,Average,4.77,54.81
4,5,24,Male,7.23,1.39,2.21,4.67,2.75,7.88,0.28,81.13,65.40,4,Good,HighSchool,Average,8.77,84.34

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     15000 non-null  int64
 1   age                            15000 non-null  int64
 2   gender                         15000 non-null  str
 3   study_hours_per_day            15000 non-null  float64
 4   smartphone_usage_hours         15000 non-null  float64
 5   social_media_hours             15000 non-null  float64
 6   gaming_hours                   15000 non-null  float64
 7   streaming_hours                15000 non-null  float64
 8   sleep_hours                    15000 non-null  float64
 9   exercise_hours                 15000 non-null  float64
 10  class_attendance_percent       15000 non-null  float64
 11  assignment_completion_percent  15000 non-null  float64
 12  caffeine_intake_cups           15000 non-null  int64
 13  mental_health_status           15000 non-null  str
 14  parent_education_level         15000 non-null  str
 15  internet_quality               15000 non-null  str
 16  motivation_level               15000 non-null  float64
 17  final_exam_score               15000 non-null  float64
dtypes: float64(11), int64(3), str(4)
memory usage: 2.1 MB

None

,student_id,age,gender,study_hours_per_day,smartphone_usage_hours,social_media_hours,gaming_hours,streaming_hours,sleep_hours,exercise_hours,class_attendance_percent,assignment_completion_percent,caffeine_intake_cups,mental_health_status,parent_education_level,internet_quality,motivation_level,final_exam_score
count,15000.000000,15000.000000,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000,15000,15000,15000.000000,15000.000000
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,3,NaN,NaN
top,NaN,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,HighSchool,Average,NaN,NaN
freq,NaN,NaN,7747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6792,6057,7564,NaN,NaN
mean,7500.500000,21.024400,NaN,4.511505,5.503475,3.516837,2.241304,1.829245,6.997377,1.234827,84.631745,79.445435,1.504933,NaN,NaN,NaN,5.988216,80.344360
std,4330.271354,2.594299,NaN,1.981043,2.437488,1.767000,1.468125,1.132042,1.456868,0.827273,9.452752,13.918023,1.227060,NaN,NaN,NaN,1.949031,18.434455
min,1.000000,17.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,3.500000,0.000000,44.960000,30.000000,0.000000,NaN,NaN,NaN,1.000000,2.630000
25%,3750.750000,19.000000,NaN,3.167500,3.830000,2.280000,1.110000,0.990000,5.970000,0.600000,78.180000,70.007500,1.000000,NaN,NaN,NaN,4.650000,68.730000
50%,7500.500000,21.000000,NaN,4.510000,5.480000,3.490000,2.175000,1.780000,6.990000,1.190000,84.895000,80.220000,1.000000,NaN,NaN,NaN,6.000000,83.745000
75%,11250.250000,23.000000,NaN,5.840000,7.150000,4.710000,3.260000,2.600000,8.030000,1.800000,91.650000,90.275000,2.000000,NaN,NaN,NaN,7.340000,97.810000
max,15000.000000,25.000000,NaN,11.780000,14.000000,9.000000,8.000000,6.000000,10.000000,4.660000,100.000000,100.000000,8.000000,NaN,NaN,NaN,10.000000,100.000000

# WIP: Cleaning data and ready for training

In [16]:
#drop unnecessary data
data.drop(columns=['parent_education_level'], inplace = True)
data.drop(columns=['internet_quality'], inplace = True)
data.drop(columns=['motivation_level'], inplace = True)
data.drop(columns=['exercise_hours'], inplace = True)
data.drop(columns=['caffeine_intake_cups'], inplace = True)

#data.dropna(axis=1, how="all", inplace=True)
#df = df.drop(columns=['column_name'])

display(data.head())
display(data.info())
display(data.describe(include="all"))

,student_id,age,gender,study_hours_per_day,smartphone_usage_hours,social_media_hours,gaming_hours,streaming_hours,sleep_hours,class_attendance_percent,assignment_completion_percent,mental_health_status,final_exam_score
0,1,21,Female,3.01,0.26,1.77,0.26,1.71,5.32,64.87,74.11,Good,82.70
1,2,23,Female,5.84,8.02,3.30,0.96,0.00,5.99,85.38,80.68,Average,85.65
2,3,20,Female,7.80,10.13,0.00,2.23,2.54,6.36,76.15,79.69,Good,88.14
3,4,20,Female,0.00,1.15,1.32,4.19,0.27,7.86,84.41,79.07,Average,54.81
4,5,24,Male,7.23,1.39,2.21,4.67,2.75,7.88,81.13,65.40,Good,84.34

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     15000 non-null  int64
 1   age                            15000 non-null  int64
 2   gender                         15000 non-null  str
 3   study_hours_per_day            15000 non-null  float64
 4   smartphone_usage_hours         15000 non-null  float64
 5   social_media_hours             15000 non-null  float64
 6   gaming_hours                   15000 non-null  float64
 7   streaming_hours                15000 non-null  float64
 8   sleep_hours                    15000 non-null  float64
 9   class_attendance_percent       15000 non-null  float64
 10  assignment_completion_percent  15000 non-null  float64
 11  mental_health_status           15000 non-null  str
 12  final_exam_score               15000 non-null  float64
dtypes: float64(9), int64(2), str(2)
memory usage: 1.5 MB

None

,student_id,age,gender,study_hours_per_day,smartphone_usage_hours,social_media_hours,gaming_hours,streaming_hours,sleep_hours,class_attendance_percent,assignment_completion_percent,mental_health_status,final_exam_score
count,15000.000000,15000.000000,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000,15000.000000
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
top,NaN,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN
freq,NaN,NaN,7747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6792,NaN
mean,7500.500000,21.024400,NaN,4.511505,5.503475,3.516837,2.241304,1.829245,6.997377,84.631745,79.445435,NaN,80.344360
std,4330.271354,2.594299,NaN,1.981043,2.437488,1.767000,1.468125,1.132042,1.456868,9.452752,13.918023,NaN,18.434455
min,1.000000,17.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,3.500000,44.960000,30.000000,NaN,2.630000
25%,3750.750000,19.000000,NaN,3.167500,3.830000,2.280000,1.110000,0.990000,5.970000,78.180000,70.007500,NaN,68.730000
50%,7500.500000,21.000000,NaN,4.510000,5.480000,3.490000,2.175000,1.780000,6.990000,84.895000,80.220000,NaN,83.745000
75%,11250.250000,23.000000,NaN,5.840000,7.150000,4.710000,3.260000,2.600000,8.030000,91.650000,90.275000,NaN,97.810000
max,15000.000000,25.000000,NaN,11.780000,14.000000,9.000000,8.000000,6.000000,10.000000,100.000000,100.000000,NaN,100.000000